networks:
  devops_net:
    driver: bridge

volumes:
  drupal_data:
  db_data:
  registry_data:

services:

  registry:
    image: registry:2
    container_name: docker_registry
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./registry/auth:/auth:ro
      - registry_data:/var/lib/registry
    networks:
      - devops_net  

  db_server:
    image: mariadb:10.11
    container_name: mariadb_container
    restart: always
    networks:
      - devops_net
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_password
    volumes:
      - db_data:/var/lib/mysql

  drupal_site:
    image: drupal:10-php8.1-apache
    container_name: drupal_container
    restart: always
    networks:
      - devops_net
    depends_on:
      - db_server
    environment:
      DRUPAL_DB_HOST: db_server
      DRUPAL_DB_NAME: drupal_db
      DRUPAL_DB_USER: drupal_user
      DRUPAL_DB_PASSWORD: drupal_password
    volumes:
      - drupal_data:/var/www/html/modules

  nginx_proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - BASIC_AUTH_USER=my_drupal_admin  # Пользователь Basic Auth (задается при сборке)
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - devops_net
    depends_on:
      - drupal_site
    environment:
      - DRUPAL_PROXY_PATH=/dp/             # Настраиваемый путь к Drupal по ТЗ
      - BASIC_AUTH_PASSWORD=my_super_password # Пароль Basic Auth (задается при запуске)
      - POPULAR_WORD=${POPULAR_WORD}          # <-- Docker Compose сам возьмет это из .env
      - WORD_FREQUENCY=${WORD_FREQUENCY}      # <-- Docker Compose сам возьмет это из .env
    volumes:
      # Сертификаты
      - ./certs/devops.crt:/etc/nginx/ssl/devops.crt:ro
      - ./certs/devops.key:/etc/nginx/ssl/devops.key:ro
      # Статика и upload
      - ./html/root:/opt/html/root
      - ./html/upload:/opt/html/upload
