---
# Переменные по умолчанию для роли docker_install

# Состояние: "present" (установить) или "absent" (удалить)
docker_state: "present"

# Версии пакетов. По умолчанию "latest" (последняя). 
# При необходимости сюда можно вписать конкретную версию, например: "5:24.0.7-1~ubuntu.22.04~jammy"
docker_version: "latest"
docker_compose_version: "latest"

# Список системных пакетов, необходимых для работы Docker
docker_required_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
