---
# Переменные по умолчанию для роли user_management

# Состояние пользователя: present (создать) или absent (удалить)
user_state: "present"

# Имя пользователя
user_name: "devops_user"

# Группы, в которые нужно добавить пользователя (по умолчанию пустой список)
user_groups: []

# Путь к оболочке (shell) по умолчанию
user_shell: "/bin/bash"

# Публичный SSH-ключ (по умолчанию пустой, замените при тестировании)
user_ssh_key: ""
